// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoleBaseAuthorization.Data;

#nullable disable

namespace RoleBaseAuthorization.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208151126_Fixed Migration")]
    partial class FixedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoleBaseAuthorization.Models.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ModuleId");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PREVIEW_DASHBOARD",
                            Description = "View dashboard previews",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Preview Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FILTER_DATE",
                            Description = "Filter data by date",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Filter Date"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DOWNLOAD",
                            Description = "Download reports/data",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Download"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ADD_STAFF",
                            Description = "Add new staff member",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Add Staff"
                        },
                        new
                        {
                            Id = 5,
                            Code = "EDIT_STAFF",
                            Description = "Edit staff information",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Edit Staff"
                        },
                        new
                        {
                            Id = 6,
                            Code = "DELETE_STAFF",
                            Description = "Delete staff member",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Delete Staff"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ADD_STUDENT",
                            Description = "Add new student",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Add Student"
                        },
                        new
                        {
                            Id = 8,
                            Code = "EDIT_STUDENT",
                            Description = "Edit student information",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Edit Student"
                        },
                        new
                        {
                            Id = 9,
                            Code = "DELETE_STUDENT",
                            Description = "Delete student",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Delete Student"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ADD_LOCATION",
                            Description = "Add new location",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Add Location"
                        },
                        new
                        {
                            Id = 11,
                            Code = "EDIT_LOCATION",
                            Description = "Edit location information",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Edit Location"
                        },
                        new
                        {
                            Id = 12,
                            Code = "DELETE_LOCATION",
                            Description = "Delete location",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Delete Location"
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentModuleId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dashboard related features",
                            DisplayOrder = 1,
                            Icon = "",
                            IsActive = true,
                            Name = "Dashboard Management"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manage staff/teachers",
                            DisplayOrder = 2,
                            Icon = "",
                            IsActive = true,
                            Name = "Staff Management"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Manage students",
                            DisplayOrder = 3,
                            Icon = "",
                            IsActive = true,
                            Name = "Student Management"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Manage locations",
                            DisplayOrder = 4,
                            Icon = "",
                            IsActive = true,
                            Name = "Location Management"
                        },
                        new
                        {
                            Id = 5,
                            Description = "View and generate reports",
                            DisplayOrder = 5,
                            Icon = "",
                            IsActive = true,
                            Name = "Reports"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Manage roles and permissions",
                            DisplayOrder = 6,
                            Icon = "",
                            IsActive = true,
                            Name = "Roles Management"
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ModuleId");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "VIEW_STATISTICS",
                            Description = "View dashboard statistics",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "View Statistics"
                        },
                        new
                        {
                            Id = 2,
                            Code = "VIEW_ENROLLMENT_ANALYTICS",
                            Description = "View enrollment analytics",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "View Enrollment Analytics"
                        },
                        new
                        {
                            Id = 3,
                            Code = "VIEW_APPLICATION_OVERVIEW",
                            Description = "View application overview",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "View Application Overview"
                        },
                        new
                        {
                            Id = 4,
                            Code = "VIEW_INTAKES_STATUS",
                            Description = "View intake status",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "View Intakes Status"
                        },
                        new
                        {
                            Id = 5,
                            Code = "VIEW_STAFF_LIST",
                            Description = "View list of staff",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "View Staff List"
                        },
                        new
                        {
                            Id = 6,
                            Code = "VIEW_STAFF_DETAILS",
                            Description = "View staff details",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "View Staff Details"
                        },
                        new
                        {
                            Id = 7,
                            Code = "VIEW_TEACHER_REPORT",
                            Description = "View teacher reports",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "View Teacher Report"
                        },
                        new
                        {
                            Id = 8,
                            Code = "VIEW_STUDENT_LIST",
                            Description = "View list of students",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "View Student List"
                        },
                        new
                        {
                            Id = 9,
                            Code = "VIEW_STUDENT_DETAILS",
                            Description = "View student details",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "View Student Details"
                        },
                        new
                        {
                            Id = 10,
                            Code = "VIEW_STUDENT_REPORT",
                            Description = "View student reports",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "View Student Report"
                        },
                        new
                        {
                            Id = 11,
                            Code = "VIEW_LOCATION_LIST",
                            Description = "View list of locations",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "View Location List"
                        },
                        new
                        {
                            Id = 12,
                            Code = "VIEW_LOCATION_DETAILS",
                            Description = "View location details",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "View Location Details"
                        },
                        new
                        {
                            Id = 13,
                            Code = "VIEW_ROLES",
                            Description = "View all roles",
                            IsActive = true,
                            ModuleId = 6,
                            Name = "View Roles"
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access - can manage everything",
                            IsSystemRole = true,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Teacher role - can manage students, view own reports",
                            IsSystemRole = false,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "School admin - can view students and teachers, but cannot delete",
                            IsSystemRole = false,
                            Name = "SchoolAdministration"
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.RoleFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId", "FunctionId")
                        .IsUnique();

                    b.ToTable("RoleFunctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FunctionId = 8,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.RolePrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("RoleId", "PrivilegeId")
                        .IsUnique();

                    b.ToTable("RolePrivileges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 18,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 19,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PrivilegeId = 10,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@ums.com",
                            FullName = "Super Administrator",
                            IsActive = true,
                            PasswordHash = "Admin@123",
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Function", b =>
                {
                    b.HasOne("RoleBaseAuthorization.Models.Module", "Module")
                        .WithMany("Functions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Module", b =>
                {
                    b.HasOne("RoleBaseAuthorization.Models.Module", "ParentModule")
                        .WithMany("SubModules")
                        .HasForeignKey("ParentModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentModule");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Privilege", b =>
                {
                    b.HasOne("RoleBaseAuthorization.Models.Module", "Module")
                        .WithMany("Privileges")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Role", b =>
                {
                    b.HasOne("RoleBaseAuthorization.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.RoleFunction", b =>
                {
                    b.HasOne("RoleBaseAuthorization.Models.Function", "Function")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RoleBaseAuthorization.Models.Role", "Role")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.RolePrivilege", b =>
                {
                    b.HasOne("RoleBaseAuthorization.Models.Privilege", "Privilege")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RoleBaseAuthorization.Models.Role", "Role")
                        .WithMany("RolePrivileges")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.UserRole", b =>
                {
                    b.HasOne("RoleBaseAuthorization.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RoleBaseAuthorization.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RoleBaseAuthorization.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Function", b =>
                {
                    b.Navigation("RoleFunctions");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Module", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("Privileges");

                    b.Navigation("SubModules");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Privilege", b =>
                {
                    b.Navigation("RolePrivileges");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.Role", b =>
                {
                    b.Navigation("RoleFunctions");

                    b.Navigation("RolePrivileges");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RoleBaseAuthorization.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
